project:
  type: website
  output-dir: docs

website:
  title: "Lauren Yehle"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching and Supervision
      - href: cv.qmd
        text: CV
  page-footer:
    left: "© Lauren Yehle" 
    right: "Built with Quarto"

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



