---
title: "Teaching and Supervision"
---
---
title: "Teaching and Supervision"
---

# Teaching and Supervision

I teach within the Department of Political Science at the University of Gothenburg at the Bachelors and Masters levels. I also teach interdisciplinary courses in the Masters Program Sea and Society affiliated with Department of Marine Sciences at the Faculty of Science and Technology. 

## Lectures

### *Environmental Politics in Theory and Practice*
*Bachelor's level, Department of Political Science, University of Gothenburg*

- **Environmental Ethics** — Lecture and seminar leader *(Fall 2026)*

### *Seascape Governance in Times of Global Change*
*Master's level, Department of Marine Sciences, University of Gothenburg*

- **Politics of Climate Change** *(Spring 2026)*

## Master's Supervision

I supervise master's theses within political science, primarily in the areas of environmental politics and public opinion.

| Student | Thesis Title | Year | Outcome|
|---------|--------------|------| -----| 
| Nils Turner | Not Set in Concrete: An Experimental Vignette Study Testing if Conservation Policy Support is Robust to Trade-offs in Housing. | 2025 | Pass with Distinction|

